### ISSUE TITLE
Errors on page 

### ISSUE THREAD

**Issue by mateuszkasiubajisc** [JiscPER/jper#58]
1)  In alerts your class - alert-messages -  not working (Reason no bootstrap.js)
a.  In Log out
b.  In incorrect log in
c.  In register user – try to register empty user
2)  Missing css files:
a.  https://pubrouter.jisc.ac.uk/static/vendor/facetview2/css/facetview.css
b.  https://pubrouter.jisc.ac.uk/static/vendor/facetview2/vendor/nvd3/nv.d3.css
3)  Uncaught ReferenceError: $ is not defined – Bad including jQuery file – This file should be included at the beginning (Header section) of the file to avoid errors like this
4)  The Question: On creating new user you try to hide/show form what is the idea? It is looks like trying to make accordion but there is a checkbox.

**Comment by markmacgillivray** [comment]
Yes, the UI we put together is minimal, and the codebase we used started from general templates. We know there are missing calls in there. These are being tidied up now, as planned in part of the code review and documentation sprint. The next push will probably remove the missing links, and then it will go up to the production machines soon. We don't include the jquery at the head because it slows page load time - not particularly relevant for this project, but a general practice. The code that has to run after the include is put into a different part of the jinja template. Not sure what you mean by point 4 - the dropdown provides further boxes to provide more info depending on the type of user you are creating.
